part of '../themes/themes.dart';

const _darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: DarkColors.primary,
  surfaceTint: DarkColors.surfaceTint,
  onPrimary: DarkColors.onPrimary,
  primaryContainer: DarkColors.primaryContainer,
  onPrimaryContainer: DarkColors.onPrimaryContainer,
  secondary: DarkColors.secondary,
  onSecondary: DarkColors.onSecondary,
  secondaryContainer: DarkColors.secondaryContainer,
  onSecondaryContainer: DarkColors.onSecondaryContainer,
  tertiary: DarkColors.tertiary,
  onTertiary: DarkColors.onTertiary,
  tertiaryContainer: DarkColors.tertiaryContainer,
  onTertiaryContainer: DarkColors.onTertiaryContainer,
  error: DarkColors.error,
  onError: DarkColors.onError,
  errorContainer: DarkColors.errorContainer,
  onErrorContainer: DarkColors.onErrorContainer,
  surface: DarkColors.surface,
  onSurface: DarkColors.onSurface,
  surfaceContainerHighest: DarkColors.surfaceVariant,
  onSurfaceVariant: DarkColors.onSurfaceVariant,
  outline: DarkColors.outline,
  outlineVariant: DarkColors.outlineVariant,
  shadow: DarkColors.shadow,
  scrim: DarkColors.scrim,
  inverseSurface: DarkColors.inverseSurface,
  inversePrimary: DarkColors.inversePrimary,
  onInverseSurface: DarkColors.onInverseSurface,
);
